export const WEATHER_INTERPRETATION_CONDE = {
  0: 'Céu limpo',
  1: 'Principalmente limpo, parcialmente nublado e encoberto',
  2: 'Principalmente limpo, parcialmente nublado e encoberto',
  3: 'Principalmente limpo, parcialmente nublado e encoberto',
  45: 'Nevoeiro e depósito de nevoeiro de geada',
  48: 'Nevoeiro e depósito de nevoeiro de geada',
  51: 'Garoa: Intensidade leve, moderada e densa',
  53: 'Garoa: Intensidade leve, moderada e densa',
  55: 'Garoa: Intensidade leve, moderada e densa',
  56: 'Garoa Congelante: Intensidade leve e densa',
  57: 'Garoa Congelante: Intensidade leve e densa',
  61: 'Chuva: Intensidade leve, moderada e forte',
  63: 'Chuva: Intensidade leve, moderada e forte',
  65: 'Chuva: Intensidade leve, moderada e forte',
  66: 'Chuva Congelante: Intensidade leve e forte',
  67: 'Chuva Congelante: Intensidade leve e forte',
  71: 'Queda de neve: Intensidade leve, moderada e forte',
  73: 'Queda de neve: Intensidade leve, moderada e forte',
  75: 'Queda de neve: Intensidade leve, moderada e forte',
  77: 'Grãos de neve',
  80: 'Pancadas de chuva: Leves, moderadas e violentas',
  81: 'Pancadas de chuva: Leves, moderadas e violentas',
  82: 'Pancadas de chuva: Leves, moderadas e violentas',
  85: 'Aguaceiros de neve leves e pesados',
  86: 'Aguaceiros de neve leves e pesados',
  95: 'Trovoada: leve ou moderada',
  96: 'Trovoada com granizo leve e forte',
  99: 'Trovoada com granizo leve e forte',
};
